### ISSUE TITLE
Letting the player select the count of how many times he wants to view the other players choice

### ISSUE THREAD

**Issue by JaloteEshi** [empiricaly/meteor-empirica-core#80] opened 2019-12-13 19:52 UTC
Is it possible to achieve this 

Hierarchy Choice: After Round 10, people need to be able to choose how much speaking time each person gets (i.e., how many times will we see person A's guess?)

Each will choose their preference for A, B, and C. For example, A may select A 3 times, B 3 times, and C 3 times. B may select A 2 times, B 5 times, and C 2 times. C may select A 2 times, B 4 times, and C 3 times. 

The actual speaking time be randomly selected from one of those 3 decisions.

**Comment by npaton** [comment] 2019-12-15 12:09
I am not sure I understand exactly the situation, sorry if I'm off-topic.

The logic for allowing players to choose their preference and then have one randomly selected should be possible with a combination of some UI work (to allow them to input their preference, and saving choices with `player.set("a", 2); player.set("b", 5); ...`), and in a onRoundEnd callback to randomly select one of the 3 decisions (for each player, collect the choices with `player.get("a") ...`, then do the random selection).

**Comment by npaton** [comment] 2019-12-31 08:00
I am closing this issue as it's not a bug, but we can keep the conversation going if needed. 👍

**Closed as completed by npaton** 2019-12-31 08:00 UTC
