### ISSUE TITLE
Issue in running experiments with multiple players

### ISSUE THREAD

**Issue by jamalx31** [empiricaly/meteor-empirica-core#49] opened 2019-02-19 17:20 UTC
We have an issue in running experiments with multiple players, the problem can be noticed with 10 players and more.
Chrome usage of CPU spikes and the experiment runs slowly, the problem isn't from the UI, disabling it didn't solve the problem.

Running experiments with the old core didn't show that problem.
Any suggestions?

## Expected Behavior
The players should enter the rounds and participate concomitantly, without lags.

## Current Behavior
The experiment runs slowly, looks like the synchronization has some lag.

## Possible Solution
The problem doesn't show with the old core.

## Steps to Reproduce (for bugs)

1. Create a batch with more than 10 players.
2. Run the experiment with 10 players (10 tabs).
3. The experiment will be sluggish.

## Context
The experiment should run smoothly.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Desktop.
- Link to your project:

**Comment by jamalx31** [comment] 2019-02-19 17:21
@npaton any thoughts?

**Comment by amaatouq** [comment] 2019-02-19 17:34
is this when you run it locally or on deployment? If in deployment, did you try to connect from more than one machine? (i.e., the lag might be from your machine having 10 browsers open and consuming your available memory).

**Comment by jamalx31** [comment] 2019-02-19 17:44
@amaatouq both, locally and deployment.
I don't think it's related to my machine since the issue doesn't happen with the old core

**Comment by amaatouq** [comment] 2019-02-19 17:54
@jamalx31 in deployment does it start and laggish or it doesn't start at all?

**Comment by jamalx31** [comment] 2019-02-19 18:02
@amaatouq It starts and sluggish

**Comment by amaatouq** [comment] 2019-02-19 18:18
@npaton could it be the db indices are missing after we changed core?

**Comment by npaton** [comment] 2019-02-19 20:23
I can reproduce the issue locally and I am not yet sure what's causing it.

I ran the experiment on the current and previous commit of your experiment, and I do notice the dramatic performance difference.

I did a pretty deep dive into the client side code to understand the source of the issue. I identified a couple of potential issues. the first is the new player presence API, which triggers a lot of extra updates, especially when switching between windows on a local test. This helps a bit, but it is still sluggish.

I ran some browser perf tests and I found a hot spot, and I can then improve performance again by deactivating a small piece of code in the data fetching, but I do not yet understand why this very small piece of code would be the source of the issue, since notably it has not changed between the 2 versions tested, and technically it does not appear clear to me why this particular piece of code would run so slowly. And even with this change, things are still slower than they used to be.

I do not think I have yet found the core issue, and I do think the couple of issues found above are just symptoms of a deeper problem.

In my tests, running a single player, things did not seem as sluggish, so I do think it should still be playable outside of a test setup with this many players running on the same machine. But this is a major issue and I will do my best to address it asap.

**Comment by amaatouq** [comment] 2019-02-20 09:13
Note: I ran an experiment with ~100 connections (8 groups of 12 people simultaneously) on the 17th of Nov 2018 with no problems! This is the last time I tested the performance of the platform—could it be something we’ve done in between?

**Comment by npaton** [comment] 2019-02-20 09:50
Well the server is not affected by the slowdown, so that's always good. And if we're running a real experiment, with participants running the client side each on their own machine, the load issue is not as apparent from my understanding. I could run an experiment with a single player locally without issues. The CPU load was just getting overall higher in the newer version of the app, which when testing with 10 players became much more apparent.

That said, the changes introduced in the latest commit on this particular experiment are way beyond just an upgrade of `empirica:core`, in the last commit the app was moved between the previous git forking model to the meteor package model, a few months difference in development, so pin pointing a potential culprit is difficult.

Also should be noted in the latest commit of this experiment, `empirica:core` is at version 0.4.0, which is from January, so the issue was not introduced since @amaatouq's latest experiment run, and nothing relevant to this type of issue was changed between 0.4 and 0.6.

I will keep looking into it, but as @amaatouq mentions here, running the actual experiment should not be a problem, but I acknowledge testing with 10 tabs locally does apparently seem more strenuous than it was a while back.

**Comment by chri4354** [comment] 2019-02-20 15:56
@npaton Perhaps the issue is on the client side, however as @jamalx31 already mentioned, we had this problem also when testing on mTurk. The number of connections that I could see on Galaxy was no more than 25 (two groups of 19 and 5 respectively). Do you suggest trying running it on the old core to see if anything changes? The app is deployed on 1 Quad container.

**Comment by npaton** [comment] 2019-02-21 09:06
@chri4354 Regarding server performance, given that @amaatouq is able to run his experiment is able to run his experiment with 4 times more people, I am not sure the issue is merely within the core. If you you want to try with the old core, and you see better performance with the old core on the server side as well, we are interested in understanding those differences.

There is 6 months of changes – including a fairly large rearchitecture of the core – between those 2 commits, and we have not had reports of such dramatic performance issues with all the experiments following along with all the changes during this time. So we are are very concerned with these issues, but it is also not clear why you are experiencing it.

**Comment by amaatouq** [comment] 2019-02-21 13:57
@npaton but I was also able at the time to test 12 players locally (a group of 12) with no problem! It seems not to be the case with Jamal’ experiment.. Let me test these things again today after I update the core.

**Comment by chri4354** [comment] 2019-03-05 14:52
We tested a batch of 49 yesterday (2 groups of 19, 2 of 5 and 1 single player) and participants in the 19 group size condition reported problems regarding extremely slow server reactions. We are reverting back to the old core, as this seemed to give us less problems. I will update this thread if this solves the problem.

**Comment by amaatouq** [comment] 2019-11-16 14:54
the problem has been identified and fixed in the updated version of empirica.

**Closed as completed by amaatouq** 2019-11-16 14:54 UTC
