### ISSUE TITLE
Players with exitStatus="playerLobbyTimedOut" assigned to game

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#39] opened 2019-01-06 20:08 UTC
Players with exitStatus="playerLobbyTimedOut" were assigned to a game.

## Expected Behavior
Players with exitStatus="playerLobbyTimedOut" should not be assigned to game.

## Current Behavior
This occurred on a somewhat overloaded server (i.e. running slowly).  My guess is that this occurred because the game started, but took long enough to initialize that the player's individual lobby timed out.

## Steps to Reproduce (for bugs)
I have not yet been able to reproduce this---will report back here when I can.

## Context
I have logic that takes the player away from the Empirica app if their lobby times out (so we can offer them alternative treatment).

As a result, the game started with players who were no longer on the Empirica app--and therefore, started with fewer than intended players.

## Your Environment
- latest Empirica
- DigitalOcean server,  Ubuntu 18.04.1 LTS, 1 vCPU, 2gb memory, 8gb swap
- 3 instances of Empirica running concurrently on the server in dev mode (3 different ports) linked to extermal MongoDB (Atlas)
- 10 concurrent users

**Comment by npaton** [comment] 2019-01-07 07:46
I haven't tested this but I can see how that might happen, your guess does sound like something possible. Even if we do improve the game init time, we should be able to lock players into the game as soon as there are enough ready, so that this situation cannot occur. I won't be addressing this directly immediately, but I will be taking this into consideration as I work on the new assignment architecture (#28), which should be able to fix this issue. Keeping open so we can check after custom assignment if the issue is still possible. Thanks!

**Comment by amaatouq** [comment] 2019-01-08 11:55
Are you sure you are not in debug mode @joshua-a-becker? it is buggy like this.

**Comment by joshua-a-becker** [comment] 2019-01-08 15:45
can confirm i am not in debug mode (actually don't know what that does)

**Comment by npaton** [comment] 2020-02-05 07:42
This is not something we will be able to fix in Empirica v1. I am closing, but it is something that will be addressed in v2.

**Closed as completed by npaton** 2020-02-05 07:42 UTC
