### ISSUE TITLE
add random playerId to "New Player" URL

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#22] opened 2018-11-04 16:43 UTC
Requested Feature--

If the playerIdParam is present in Meteor.public settings, add a random playerId to the URL for the "new player" button for dev's.

Argument for adding this feature:  if people want their dev tests to involve manually entering a playerId, they can just leave this param undefined in settings.json, and adding the param in settings implies you expect playerId to come through the URL.

This is pretty trivial and I'd be happy to add it via pull request, if you can offer a recommendation on how I can test changes to Meteor core.

**Comment by npaton** [comment] 2018-11-05 07:39
No problem with the feature overall, we do need to improve dev/debug. I don't think mixing the playerParamId and New Player is particularly beneficial. We can add an option to make New Player automatically "logging in" the player with a random ID.

The reasoning here is about keeping things clear and obvious, as much as possible. Mixing the playerParamId option with some sort of automatic logging that only works in dev is an unexpected behavior that might surprise people as it's inconsistent depending on environments. I (generally) don't want any behavior to be dependent entirely on environment, everything should be configurable. This is actually broken at the moment, there are some debugging options that are forced on in dev, I ultimately don't want this (see new config bellow). Here, adding a simple configuration option, allows people to control this behavior; and in this case, to also be able to use it in "production", e.g. a deployed testing environment.

Maybe something like `public.debug_newPlayerAutoLogIn` , boolean. I don't like "log in" much, but maybe it's ok. Registration? Sign up? Connection?

Note: I am not a fan of our current app configuration situation. Ultimately, I want to separate meteor/deployment configuration, our current settings.json file, and app configuration, which could be committed into the repo, be something easier to edit by hand and comment like YAML; something where we can generate good development and production defaults with create-empirica-app (instead of using environment variables as we are doing right now), and maybe even hierarchical. So I'm sorry for the long and ugly naming, I should get better when we get to the new config style.

**Comment by joshua-a-becker** [comment] 2018-11-05 13:30
How could this ever be used in staging / deployed testing environment?

I think that this behaviori would be expected, under the assumption that:  if I have playerIdParam set (which could vary by which settings.json I use) then I don’t expect people to manually enter a playerId, therefore automated playerId is expected.

Though I’d also find it just as useful if that were handled by a separate config.

On the issue of settings—-I don’t find it desirable to redeploy at all to change settings, I.e. I cannot change settings on Galaxy without waiting a few minutes.  I would prefer a browser-based settings option in the admin panel.  (Happy to share code for the crude one I’ve been using, but I think that should be a separate issue)

**Comment by joshua-a-becker** [comment] 2018-11-05 13:32
> How could this ever be used in staging / deployed testing environment?

Realized we may be talking about two different implementations—I’m imagining the playerId added to you might be suggesting auto registration even without the ID passed to the url.

**Comment by npaton** [comment] 2018-11-05 13:59
> > How could this ever be used in staging / deployed testing environment?
> 
> Realized we may be talking about two different implementations—I’m imagining the playerId added to you might be suggesting auto registration even without the ID passed to the url.

Yes, it would work, even if not using playerParamId. ;)

**Comment by npaton** [comment] 2018-11-05 14:02
> On the issue of settings—-I don’t find it desirable to redeploy at all to change settings, I.e. I cannot change settings on Galaxy without waiting a few minutes. I would prefer a browser-based settings option in the admin panel. (Happy to share code for the crude one I’ve been using, but I think that should be a separate issue)

I understand, it can make sense to go into the UI, it also makes sense to be able to easily share configuration, we'll discuss about it before moving forward. ;)

**Comment by amaatouq** [comment] 2018-11-06 01:38
a related thing would be: if in `debug` mode you skip everything (consent, taking user id, intro) and go to the lobby directly (i.e., use `_id` as `id`). Also, maybe we want an option somewhere that specifies without the debug mode.

**Comment by joshua-a-becker** [comment] 2018-12-31 19:22
this appears to be done!

**Comment by joshua-a-becker** [comment] 2019-01-06 18:55
sorry for the noise---i was wrong, i was looking at my own repo and not the upstream repo.

**Comment by joshua-a-becker** [comment] 2019-02-26 20:40
Proposing a pull request

Functionality;  adds the playerIdParam to URL *if required*

**Comment by npaton** [comment] 2019-02-27 16:24
This should be fixed by #50 in `0.7.0`. ⛵️

**Closed as completed by npaton** 2019-02-27 16:24 UTC
