### ISSUE TITLE
Player data removed upon game start

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/meteor-empirica-core#37] opened 2019-01-03 19:26 UTC
Player data set during intro steps is removed during game start.

## Expected Behavior
Player data set during intro steps will be persistent in the db.

## Possible Solution
remove line 45 in `/api/games/create.js`

## Notes
I'm a bit slow on github, and will submit a pull request this weekend if you don't beat me to it.

**Comment by npaton** [comment] 2019-01-07 07:58
Agreed the issue might be on line 45 of `/api/games/create.js`. Maybe:

```js
player.data = player.data || {};
```

Not sure if there are still cases where `player.data` might be undefined, so it might still need  to be initialized with `{}`. I haven't had the time to look into it deeper, but a PR would be welcome. 💃 It's a quick fix, adding to my next tasks if no one gets to it before me. ;)

**Comment by eamanj** [comment] 2019-01-16 18:12
I have the same problem. Josh, could you post a code snippet how you set the player attribs?

**Comment by joshua-a-becker** [comment] 2019-01-16 18:19
I literally just removed line 45 in `/api/games/create.js`

@npaton is concerned this may leave the player.data object uninitialized, but my quick test showed that the default is `{}`.    Just keep any eye out for possible errors related to this, or use something more like the line that Nicolas gives above.   

Sorry I haven't had a chance to do a pull request!

**Comment by eamanj** [comment] 2019-01-16 19:22
@joshua-a-becker  I removed line 45 and still get the same issue. doing what @npaton suggested did not fix it either. I suspect, it is because my pre-survey is not done correctly. I basically copied the exitsurvey and changed it so it matches the intro stages. See the code:
```
  static stepName = "InitialSurvey";
  state = { age: "", education: "", gender: "", political_affiliation: "" };

  handleChange = event => {
    const el = event.currentTarget;
    this.setState({ [el.name]: el.value }); 
  };  

  handleSubmit = event => {
    event.preventDefault();
    const { player } = this.props;
    for (var key in this.state) {
      player.set(key, this.state[key]);
    }   
    console.log(player)
    this.props.onNext();
  };  

```

**Comment by joshua-a-becker** [comment] 2019-01-17 03:44
Can you share the entire file, or perhaps you have an entire repo I could clone?

I can't tell just by reading that what might be going wrong---I'm not good enough at javascript to spot potential errors.

The first thing I'd check is whether the player data is being properly set even in that moment---whether the issue is that it's being later erased, or whether it's never being set in the first place.

**Comment by eamanj** [comment] 2019-01-17 19:26
I did log the attributes in the intro-survey. They do get set correctly, but when I log the player in the game, the attributes are no longer there. Here is the code snippet from client/main.js:
```
Empirica.introSteps(game => {
  const steps = [InitialSurvey, Overview];
  ...
  return steps;
});
```

Here is the InitialSurvey.js:
```
import React from "react";

import { Centered } from "meteor/empirica:core";

const Radio = ({ selected, name, value, label, onChange }) => (
  <label>
    <input
      type="radio"
      name={name}
      value={value}
      checked={selected === value}
      onChange={onChange}
    />
    {label}
  </label>
);


export default class InitialSurvey extends React.Component {
  state = { age: "", education: "", gender: "", political_affiliation: "" };
  constructor(props) {
    super(props);
  }

  handleChange = event => {
    const el = event.currentTarget;
    this.setState({ [el.name]: el.value.trim().toLowerCase() });
  };

  handleSubmit = event => {
    event.preventDefault();
    const { player } = this.props;
    for (var key in this.state) {
      player.set(key, this.state[key]);
    }
    this.props.onNext();
    console.log(player.get("political_affiliation"))
  };

  render() {
    const { age, gender, education, political_affiliation } = this.state;

    return (
      <Centered>
        <div className="initial-survey">
          <h1> Initial Survey </h1>
          <br />
          <p>
            Please answer the following short survey. You do not have to provide
            any information you feel uncomfortable with.
          </p>
          <form onSubmit={this.handleSubmit}>
            <div className="form-line">
              <div>
                <label htmlFor="age" className="boldlabel">Age</label>
                <div>
                  <input
                    id="age"
                    type="number"
                    min="0"
                    max="150"
                    step="1"
                    dir="auto"
                    name="age"
                    value={age}
                    onChange={this.handleChange}
                  />
                </div>
              </div>
              <div>
                <label htmlFor="gender" className="boldlabel">Gender</label>
                <div>
                  <input
                    id="gender"
                    type="text"
                    dir="auto"
                    name="gender"
                    value={gender}
                    onChange={this.handleChange}
                    autoComplete="off"
                  />
                </div>
              </div>
            </div>

            <div>
              <label className="boldlabel">Highest Education Qualification</label>
              <div>
                <Radio
                  selected={education}
                  name="education"
                  value="high-school"
                  label="High School"
                  onChange={this.handleChange}
                />
                <Radio
                  selected={education}
                  name="education"
                  value="bachelor"
                  label="Bachelor's Degree"
                  onChange={this.handleChange}
                />
                <Radio
                  selected={education}
                  name="education"
                  value="master"
                  label="Master's or higher"
                  onChange={this.handleChange}
                />
                <Radio
                  selected={education}
                  name="education"
                  value="other"
                  label="Other"
                  onChange={this.handleChange}
                />
              </div>
            </div>

            <div>
              <label className="boldlabel">Political Affiliation</label>
              <div>
                <Radio
                  selected={political_affiliation}
                  name="political_affiliation"
                  value="democrat"
                  label="Democrat"
                  onChange={this.handleChange}
                />
                <Radio
                  selected={political_affiliation}
                  name="political_affiliation"
                  value="republican"
                  label="Republican"
                  onChange={this.handleChange}
                />
                <Radio
                  selected={political_affiliation}
                  name="political_affiliation"
                  value="independent"
                  label="Independent"
                  onChange={this.handleChange}
                />
              </div>
            </div>

            <button type="submit">Submit</button>
          </form>
        </div>
      </Centered>
    );





```

**Comment by joshua-a-becker** [comment] 2019-01-17 19:29
And you can confirm that your updates to core are being reflected in the app----i.e., you're using the local package source instead of the default core package location?

**Comment by eamanj** [comment] 2019-01-17 19:35
that's a good point. How do I check which package I am using?

**Comment by joshua-a-becker** [comment] 2019-01-17 19:40
You can check by, e.g., changing something visible in the admin interface or adding a console log in one of the scripts.  

And make sure you're running your app with the `METEOR_PACKAGE_DIRS` variable set, for example:

`[user@linux]$  METEOR_PACKAGE_DIRS=/home/location-of-custom-core meteor`

**Comment by joshua-a-becker** [comment] 2019-01-17 19:50
^^that "location of custom core" should be the root folder of your clone of the `meteor-empirica-core` repo

**Comment by amaatouq** [comment] 2019-01-17 19:52
I talked with @npaton today and this should be fixed by tomorrow morning in the main repo.

**Comment by eamanj** [comment] 2019-01-17 19:53
I added a console log in create.js and changed the core dir as follows:
export METEOR_PACKAGE_DIRS="/home/eaman/research/polarization/meteor-empirica-core/"

The message did not appear and player attribs were not set. But I am not sure if the message was supposed to appear, since it might be running on server side..

**Comment by eamanj** [comment] 2019-01-17 19:53
@amaatouq good to know! thanks

**Comment by joshua-a-becker** [comment] 2019-01-17 19:54
i never got it to work with that method, i'm not that great at linux.

if you can't wait until tomorrow, try running meteor with the command i gave above.

**Comment by eamanj** [comment] 2019-01-17 19:55
@joshua-a-becker thanks for the help. will wait until tomorrow.

**Comment by npaton** [comment] 2019-01-18 01:35
I push a fix that should resolve this issue. Run `meteor update empirica:core` and let me know if you are still seeing issue. If none found, feel free to close the issue. Sorry for the delay. ⛵️

**Comment by eamanj** [comment] 2019-01-18 18:15
@npaton thanks for the fix. It did work and player data carried through to game stage. FWIW, server spit out an error that was not happening before. This happened right after I submitted the initial survey:

```
I20190118-13:12:07.360(-5)? Exception while invoking method 'Players.methods.updateData' { MongoError: Updating the path 'data' would create a conflict at 'data'
I20190118-13:12:07.382(-5)?     at Function.create (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:43:12)
I20190118-13:12:07.383(-5)?     at toError (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20190118-13:12:07.383(-5)?     at coll.s.topology.update (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
I20190118-13:12:07.384(-5)?     at /home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:532:18
I20190118-13:12:07.384(-5)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20190118-13:12:07.384(-5)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20190118-13:12:07.384(-5)?   driver: true,
I20190118-13:12:07.384(-5)?   name: 'MongoError',
I20190118-13:12:07.384(-5)?   index: 0,
I20190118-13:12:07.385(-5)?   code: 40,
I20190118-13:12:07.385(-5)?   errmsg: 'Updating the path \'data\' would create a conflict at \'data\'',
I20190118-13:12:07.385(-5)?   [Symbol(mongoErrorContextSymbol)]: {} }
I20190118-13:12:07.385(-5)? Exception while invoking method 'Players.methods.updateData' { MongoError: Updating the path 'data' would create a conflict at 'data'
I20190118-13:12:07.385(-5)?     at Function.create (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:43:12)
I20190118-13:12:07.385(-5)?     at toError (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
I20190118-13:12:07.386(-5)?     at coll.s.topology.update (/home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
I20190118-13:12:07.386(-5)?     at /home/eaman/.meteor/packages/npm-mongo/.3.1.1.1ppa6aa.kzds++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:532:18
I20190118-13:12:07.386(-5)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20190118-13:12:07.386(-5)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20190118-13:12:07.386(-5)?   driver: true,
I20190118-13:12:07.386(-5)?   name: 'MongoError',
I20190118-13:12:07.386(-5)?   index: 0,
I20190118-13:12:07.386(-5)?   code: 40,
I20190118-13:12:07.386(-5)?   errmsg: 'Updating the path \'data\' would create a conflict at \'data\'',
I20190118-13:12:07.386(-5)?   [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by npaton** [comment] 2019-01-22 01:37
I haven't been able to reproduce this error. Is this happening systematically every time you submit the survey? I would probably need to be able to run the code to investigate further, if that's something you can do. Thanks!

**Comment by joshua-a-becker** [comment] 2019-02-26 20:34
@eamanj for future reference---the `METEOR_PACKAGE_DIRS` var should be set to the folder *containing* the folder, so in your case it would be:

METEOR_PACKAGE_DIRS=/home/eaman/research/polarization/

**Comment by amaatouq** [comment] 2019-11-16 14:58
is this fixed now, @npaton?

**Comment by npaton** [comment] 2019-11-16 14:59
I believe it is. Please reopen if you are still having issues here.

**Closed as completed by npaton** 2019-11-16 14:59 UTC
