### ISSUE TITLE
Mongo disconnections allow timer to go under 0, Mongo does not automatically reconnect

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#69] opened 2019-11-16 16:23 UTC
I sometimes get another error in production that has never happened locally. The game has five stages and each stage has 30 seconds. The game proceeds to the next stage when both the bot and the player submit. The bot is guaranteed to submit within 30 seconds. This works fine but sometimes in production the game does not proceed to the next stage and timer goes into negative numbers. Not sure exactly why this happens as the last time it happened there were no errors in meteor logs. The first time it happened though, it had coincided with a restart of the mongodb server.

any ideas?

**Comment by npaton** [comment] 2019-11-16 16:44
This could currently happen if the server is unresponsive. I am working on a fix to stop showing the round UI after the timer reaches 0. When the server is ready again, things should update automatically.

If you need to fix this immediately, a props is passed to the Round component called `ended` that is true when the the stage has ended, and you can remove the round UI with that. In the next update, we will make that the default behavior.

**Comment by eamanj** [comment] 2019-11-16 19:31
Just to clarify, once this happens, it happens for all the subsequent players. The fix is to restart the meteor app, as if the error hangs the server and it never recovers. But it would be good to investigate why it gets to that state.

**Comment by npaton** [comment] 2019-11-17 00:46
I will look into it.

**Comment by amaatouq** [comment] 2019-11-17 00:52
A few thoughts. 

You might need something like this for the bot if you are using `onStageTick' Otherwise, the bot can overwhelm the server:
```javascript
if (bot.stage.submitted) { return;}
```

Also, you want to have something like this `onRoundStart(.)`: 

```javascript
player.round.set("prediction", null);
```
Because you might be trying to read or compute something entered by the user, but the variable is never set (i.e., the participant is idle).

**Comment by hubertusputu1** [comment] 2020-03-17 03:22
Hello @eamanj , since we cannot reproduce this issue, we will close it for now. If this issue still happening to someone, they can reopen with further context information. Thank You.

**Closed as completed by hubertusputu1** 2020-03-17 03:22 UTC
